import fsp from "node:fs/promises";
import path from "node:path";
import { marked } from "marked";
import { createPool } from "../util/pool.js";
import { KATEX_CSS_FILENAME, SEARCH_BOOTSTRAP_JS } from "./clientAssets.js";
import { escapeHtmlText as htmlEscape } from "./htmlEscape.js";
import { safeSegment } from "./paths.js";
import { STYLE_CSS } from "./styles.js";

marked.setOptions({ gfm: true, breaks: false });

const STYLE_FILENAME = "style.css";
const GITHUB_URL = "https://github.com/dmetzner/notion-exporter";

// Theme-switcher icons — shared by the per-page topbar (`renderHtml`) and the
// archive index (`writeSitemap`). Extracted so the SVG paths live in exactly
// one place; previously each renderer had its own copy.
const THEME_SVG_LIGHT = `<svg viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.93 4.93l1.41 1.41M17.66 17.66l1.41 1.41M2 12h2M20 12h2M4.93 19.07l1.41-1.41M17.66 6.34l1.41-1.41"/></svg>`;
const THEME_SVG_SYSTEM = `<svg viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="3" y="4" width="18" height="13" rx="2"/><path d="M8 21h8M12 17v4"/></svg>`;
const THEME_SVG_DARK = `<svg viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"/></svg>`;

/** The three theme switcher buttons (light / system / dark) — just the
 * `<button>` lines without the surrounding `<div class="topbar-theme">`. Each
 * caller wraps in its own group div so the closing-tag layout matches the
 * existing per-page (closes on its own line) vs. index (joined to last
 * button) snapshots. */
const STATS_ICON_SVG = `<svg viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" aria-hidden="true"><line x1="6" y1="20" x2="6" y2="12"/><line x1="12" y1="20" x2="12" y2="6"/><line x1="18" y1="20" x2="18" y2="14"/></svg>`;

function statsButton(idx: string): string {
  return `<a class="topbar-stats" href="${idx}stats.html" title="Workspace statistics" aria-label="Workspace statistics">${STATS_ICON_SVG}</a>`;
}

const THEME_BUTTONS = `<button type="button" class="theme-btn" data-theme-set="light" aria-label="Light theme" title="Light">${THEME_SVG_LIGHT}</button>
    <button type="button" class="theme-btn" data-theme-set="system" aria-label="System theme" title="System">${THEME_SVG_SYSTEM}</button>
    <button type="button" class="theme-btn" data-theme-set="dark" aria-label="Dark theme" title="Dark">${THEME_SVG_DARK}</button>`;

function renderFooter(pageBits = ""): string {
  const year = new Date().getFullYear();
  const pageRow = pageBits ? `<div class="footer-row footer-page">${pageBits}</div>` : "";
  return `<footer class="site-footer">
  ${pageRow}
  <div class="footer-row footer-meta">
    <span class="footer-brand">Generated by <a href="${GITHUB_URL}" rel="noopener" target="_blank">notion-exporter</a></span>
    <span class="footer-copy">&copy; ${year}</span>
  </div>
</footer>`;
}

function subdirDepth(subdir: string): number {
  return subdir ? subdir.split(path.sep).filter(Boolean).length : 0;
}

export function assetPrefix(subdir: string): string {
  return "../".repeat(subdirDepth(subdir) + 1);
}

export function indexPrefix(subdir: string): string {
  return "../".repeat(subdirDepth(subdir));
}

export interface RenderOpts {
  assetPrefix?: string;
  indexPrefix?: string;
  archiveTitle?: string;
  /** Workspace icon shown in the sidebar header. Single emoji glyph OR an
   * absolute http(s) URL OR an html-root-relative path. Default 📚. */
  archiveIcon?: string;
  /** Page icon used to build the browser-tab favicon. */
  favicon?: { kind: "emoji" | "image"; value: string };
  /** Pre-rendered HTML version of the page title, used in the topbar
   * breadcrumb tail so `:custom_emoji:` references show as inline images
   * instead of literal text. Falls back to the escaped plain title. */
  pageTitleHtml?: string;
  /** When true, paragraphs containing a single `↩️ …` link get tagged with
   * `class="back-link"` so the stylesheet can render them as a back-button. */
  styleBackLinks?: boolean;
}

// Render the sidebar-home glyph from the configured EXPORT_ICON value:
// - single emoji → emit verbatim (font handles it)
// - http(s) URL  → <img> with the URL
// - export-root-relative `assets/...` → prefix with `assetPrefix` so the path
//   walks back out of `html/<subdir>/` to the export root
// - other relative path → prefix with `indexPrefix` (treats path as
//   html-root-relative, e.g. a file the user placed inside html/)
function renderArchiveIcon(
  icon: string | undefined,
  idxPrefix: string,
  assetPrefix: string,
): string {
  const v = (icon ?? "").trim();
  if (!v) return "📚";
  const escaped = htmlEscape(v);
  if (/^https?:\/\//i.test(v)) {
    return `<img class="sidebar-home-icon" src="${escaped}" alt="" loading="lazy">`;
  }
  if (v.startsWith("assets/")) {
    return `<img class="sidebar-home-icon" src="${htmlEscape(assetPrefix)}${escaped}" alt="" loading="lazy">`;
  }
  if (v.includes("/") || /\.(png|jpg|jpeg|svg|webp|gif)$/i.test(v)) {
    return `<img class="sidebar-home-icon" src="${htmlEscape(idxPrefix)}${escaped}" alt="" loading="lazy">`;
  }
  return escaped;
}

// `<title>` only accepts text, so Notion `:name:` custom-emoji shortcodes
// can't render as images there. Strip them so the browser tab shows
// "Roadmap" instead of "Roadmap :rocket:". Trims any whitespace runs
// left behind.
function titleForTab(title: string): string {
  return (
    title
      .replace(/:[a-zA-Z0-9_\-+]+:/g, "")
      .replace(/\s+/g, " ")
      .trim() || title
  );
}

function renderFavicon(icon?: { kind: "emoji" | "image"; value: string }): string {
  if (!icon) return "";
  if (icon.kind === "image") {
    return `<link rel="icon" href="${htmlEscape(icon.value)}">`;
  }
  // Emoji → inline SVG data URI so the tab favicon matches the page icon.
  // htmlEscape the value first so a malicious operator-controlled string
  // can't break out of the <text> element inside the SVG payload.
  const svg = `<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><text y='.9em' font-size='90'>${htmlEscape(icon.value)}</text></svg>`;
  return `<link rel="icon" href="data:image/svg+xml,${encodeURIComponent(svg)}">`;
}

export function renderHtml(title: string, markdown: string, opts: RenderOpts = {}): string {
  const assets = opts.assetPrefix ?? "../";
  const idx = opts.indexPrefix ?? "";
  const archiveTitle = opts.archiveTitle ?? "Your Notion archive";
  let body = marked.parse(markdown) as string;
  // `data="assets/…"` covers the PDF `<object data=…>` embed emitted by
  // `renderPdfBlock`. Without it, PDFs on nested pages 404 because the
  // rewrite never fires.
  //
  // The lookbehind anchor (`\s`/`<`) ensures we only match attributes at a
  // genuine tag-boundary — without it the bare `data` alternative is a
  // suffix of `metadata="…"`/`itemdata="…"`/etc. and would partial-match,
  // corrupting future attributes that happen to share the suffix.
  body = body.replace(/(?<=[\s<])(src|href|data)="assets\//g, `$1="${assets}assets/`);
  // Cross-page links are emitted as .md paths in the markdown layer; swap to .html
  // so they resolve correctly when viewed from the html/ output.
  body = body.replace(/href="([^"]+)\.md(#[^"]*)?"/g, 'href="$1.html$2"');
  // Opt-in: paragraphs containing a single ↩️ link get tagged so the
  // stylesheet can render them as a back-button. Matches the leading-↩️
  // convention some Notion users employ to provide an explicit "Back to
  // <parent>" affordance below the H1.
  if (opts.styleBackLinks) {
    body = body.replace(
      /<p>\s*(<a\s[^>]*>\s*↩️?\s+[^<]*<\/a>)\s*<\/p>/g,
      '<p class="back-link">$1</p>',
    );
  }
  // Pull cover out of body so we can render it edge-to-edge at the very top,
  // with breadcrumbs/topbar BELOW the image.
  let cover = "";
  const coverMatch = body.match(/^\s*<p class="cover">[\s\S]*?<\/p>\s*/);
  if (coverMatch) {
    cover = coverMatch[0];
    body = body.slice(coverMatch[0].length);
  }
  // Pull breadcrumbs out of the body so they can live in the sticky topbar,
  // and always prefix the chain with a link to the archive index.
  const archiveCrumb = `<a href="${idx}index.html" title="${htmlEscape(archiveTitle)}">${htmlEscape(archiveTitle)}</a>`;
  let crumbInner = archiveCrumb;
  const crumbsMatch = body.match(/<nav class="breadcrumbs">([\s\S]*?)<\/nav>\s*/);
  if (crumbsMatch) {
    crumbInner += crumbsMatch[1] ?? "";
    body = body.replace(crumbsMatch[0], "");
  }
  // Append the current page title as a non-link tail so long-scrolling pages
  // keep a "you are here" affordance once the H1 leaves the viewport.
  crumbInner += `<span class="breadcrumb-current" aria-current="page" title="${htmlEscape(title)}">${opts.pageTitleHtml ?? htmlEscape(title)}</span>`;
  const crumbs = `<nav class="breadcrumbs">${crumbInner}</nav>`;
  // Pull the markdown-emitted page-footer bits out of the body so we can merge
  // them into the single site footer.
  let pageBits = "";
  const pageFooterMatch = body.match(/<footer class="page-footer">([\s\S]*?)<\/footer>\s*/);
  if (pageFooterMatch) {
    pageBits = pageFooterMatch[1] ?? "";
    body = body.replace(pageFooterMatch[0], "");
  }
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${htmlEscape(titleForTab(title))}</title>
${renderFavicon(opts.favicon)}
<link rel="stylesheet" href="${idx}${STYLE_FILENAME}">
<link rel="stylesheet" href="${idx}${KATEX_CSS_FILENAME}">
<script>try{var t=localStorage.getItem('ne-theme');if(t==='dark'||t==='light')document.documentElement.setAttribute('data-theme',t);}catch(e){}</script>
</head>
<body class="has-sidebar" data-root-prefix="${idx}">
<input id="ne-sb-toggle" type="checkbox" hidden>
<script>try{if(window.matchMedia('(min-width:900px)').matches&&localStorage.getItem('ne-sb-collapsed')==='1')document.getElementById('ne-sb-toggle').checked=true;}catch(e){}</script>
<div class="app">
<aside class="sidebar">
  <div class="sidebar-head">
    <a class="sidebar-home" href="${idx}index.html" title="${htmlEscape(archiveTitle)}">${renderArchiveIcon(opts.archiveIcon, idx, assets)}<span class="sidebar-home-title">${htmlEscape(archiveTitle)}</span></a>
  </div>
  <form class="sidebar-search" onsubmit="return false">
    <input id="ne-sidebar-search" data-ne-search type="search" placeholder="Search…" autocomplete="off">
  </form>
  <ol id="ne-sidebar-results" class="ne-results" hidden></ol>
  <nav class="sidebar-nav" data-ne-tree><!--NE_SIDEBAR--></nav>
</aside>
<label class="sidebar-scrim" for="ne-sb-toggle" aria-hidden="true"></label>
<div class="main-col">
<header class="topbar">
  <label class="topbar-toggle" for="ne-sb-toggle" aria-label="Toggle navigation" title="Toggle navigation"><svg class="icon-open" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.25" stroke-linecap="round" aria-hidden="true"><path d="M4 7h16M4 12h16M4 17h16"/></svg><svg class="icon-close" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.25" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M14 6l-6 6 6 6"/></svg></label>
  <div class="topbar-crumbs">${crumbs}</div>
  ${statsButton(idx)}
  <div class="topbar-theme" role="group" aria-label="Theme">
    ${THEME_BUTTONS}
  </div>
</header>
<main class="layout">
${cover}${body}
${renderFooter(pageBits)}
</main>
</div>
</div>
<script src="${idx}search.js" defer></script>
<script src="${idx}lightbox.js" defer></script>
<!-- Lazy-load lunr.min.js + search-index.js on first interaction with the
     search box. Filenames live as strings inside this bootstrap so the
     network cost is deferred until the user actually opens search. -->
<script>${SEARCH_BOOTSTRAP_JS}window.__NE_BOOT_SEARCH(${JSON.stringify(idx)});</script>
</body>
</html>
`;
}

export async function writeHtml(
  htmlDir: string,
  doc: { id: string; title: string; fallbackTitle?: string },
  markdown: string,
  subdir = "",
  opts: {
    archiveTitle?: string;
    archiveIcon?: string;
    favicon?: { kind: "emoji" | "image"; value: string };
    pageTitleHtml?: string;
    styleBackLinks?: boolean;
  } = {},
): Promise<string> {
  const filename = `${safeSegment(doc.title)}.${doc.id}.html`;
  const abs = path.join(htmlDir, subdir, filename);
  await fsp.mkdir(path.dirname(abs), { recursive: true });
  const title = doc.title || doc.fallbackTitle || "(untitled)";
  await fsp.writeFile(
    abs,
    renderHtml(title, markdown, {
      assetPrefix: assetPrefix(subdir),
      indexPrefix: indexPrefix(subdir),
      archiveTitle: opts.archiveTitle,
      archiveIcon: opts.archiveIcon,
      favicon: opts.favicon,
      pageTitleHtml: opts.pageTitleHtml,
      styleBackLinks: opts.styleBackLinks,
    }),
  );
  return abs;
}

export async function writeStylesheet(htmlDir: string): Promise<string> {
  const abs = path.join(htmlDir, STYLE_FILENAME);
  await fsp.writeFile(abs, STYLE_CSS);
  return abs;
}

export interface ChromeOpts {
  /** Document title for the browser tab. */
  title: string;
  /** Body content placed inside `<main class="layout">`. */
  bodyHtml: string;
  /** Trailing breadcrumb after the archive home link (e.g. "Statistics"). */
  breadcrumbTail?: string;
  /** Pre-rendered HTML for the trailing breadcrumb when the tail contains
   * inline markup (custom emoji etc.). Falls back to escaped `breadcrumbTail`. */
  breadcrumbTailHtml?: string;
  /** Relative prefix from this page back to html/. "" for files in html/. */
  idx?: string;
  archiveTitle?: string;
  archiveIcon?: string;
  favicon?: { kind: "emoji" | "image"; value: string };
  /** Extra body class (concatenated with "has-sidebar"). */
  bodyClass?: string;
}

/** Render the full page chrome (sidebar + topbar + main) around arbitrary
 * `<main>` content. Mirrors the shell built by `renderHtml` for content pages
 * — used by stats.html (and any future static pages) so they share the same
 * nav, search box, theme toggle, and breadcrumb pattern.
 *
 * Emits `<!--NE_SIDEBAR-->` inside the nav so `injectSidebars` can stamp the
 * shared tree skeleton into the file in its finalize pass. */
export function renderChrome(opts: ChromeOpts): string {
  const idx = opts.idx ?? "";
  const assets = `${idx}../`;
  const archiveTitle = opts.archiveTitle ?? "Your Notion archive";
  const tailHtml =
    opts.breadcrumbTailHtml ?? (opts.breadcrumbTail ? htmlEscape(opts.breadcrumbTail) : "");
  const crumb = `<nav class="breadcrumbs"><a href="${idx}index.html" title="${htmlEscape(archiveTitle)}">${htmlEscape(archiveTitle)}</a>${tailHtml ? `<span class="breadcrumb-current" aria-current="page">${tailHtml}</span>` : ""}</nav>`;
  const bodyClasses = `has-sidebar${opts.bodyClass ? ` ${opts.bodyClass}` : ""}`;
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${htmlEscape(titleForTab(opts.title))}</title>
${renderFavicon(opts.favicon)}
<link rel="stylesheet" href="${idx}${STYLE_FILENAME}">
<link rel="stylesheet" href="${idx}${KATEX_CSS_FILENAME}">
<script>try{var t=localStorage.getItem('ne-theme');if(t==='dark'||t==='light')document.documentElement.setAttribute('data-theme',t);}catch(e){}</script>
</head>
<body class="${bodyClasses}" data-root-prefix="${idx}">
<input id="ne-sb-toggle" type="checkbox" hidden>
<script>try{if(window.matchMedia('(min-width:900px)').matches&&localStorage.getItem('ne-sb-collapsed')==='1')document.getElementById('ne-sb-toggle').checked=true;}catch(e){}</script>
<div class="app">
<aside class="sidebar">
  <div class="sidebar-head">
    <a class="sidebar-home" href="${idx}index.html" title="${htmlEscape(archiveTitle)}">${renderArchiveIcon(opts.archiveIcon, idx, assets)}<span class="sidebar-home-title">${htmlEscape(archiveTitle)}</span></a>
  </div>
  <form class="sidebar-search" onsubmit="return false">
    <input id="ne-sidebar-search" data-ne-search type="search" placeholder="Search…" autocomplete="off">
  </form>
  <ol id="ne-sidebar-results" class="ne-results" hidden></ol>
  <nav class="sidebar-nav" data-ne-tree><!--NE_SIDEBAR--></nav>
</aside>
<label class="sidebar-scrim" for="ne-sb-toggle" aria-hidden="true"></label>
<div class="main-col">
<header class="topbar">
  <label class="topbar-toggle" for="ne-sb-toggle" aria-label="Toggle navigation" title="Toggle navigation"><svg class="icon-open" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.25" stroke-linecap="round" aria-hidden="true"><path d="M4 7h16M4 12h16M4 17h16"/></svg><svg class="icon-close" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.25" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M14 6l-6 6 6 6"/></svg></label>
  <div class="topbar-crumbs">${crumb}</div>
  ${statsButton(idx)}
  <div class="topbar-theme" role="group" aria-label="Theme">
    ${THEME_BUTTONS}
  </div>
</header>
<main class="layout">
${opts.bodyHtml}
${renderFooter()}
</main>
</div>
</div>
<script src="${idx}search.js" defer></script>
<script src="${idx}lightbox.js" defer></script>
<script>${SEARCH_BOOTSTRAP_JS}window.__NE_BOOT_SEARCH(${JSON.stringify(idx)});</script>
</body>
</html>
`;
}

export interface SitemapIcon {
  kind: "emoji" | "image";
  // emoji char OR export-root-relative asset path (e.g. "assets/abc.png")
  value: string;
}

export interface SitemapEntry {
  id: string;
  title: string;
  href: string;
  kind: "page" | "database";
  parentId?: string;
  icon?: SitemapIcon;
  /** Position within parent (Notion's child_page order). Lower = earlier.
   * When unset, the tree falls back to alphabetical sort. */
  position?: number;
  /** Pre-rendered HTML title (e.g. `:rocket:` swapped for an `<img>`). Uses
   * root-relative `assets/<hash>.…` paths so injectSidebars can rewrite
   * them to per-page-depth-relative paths. */
  titleHtml?: string;
}

interface TreeNode {
  id: string;
  title: string;
  titleHtml?: string;
  href: string;
  kind: "page" | "database";
  icon?: SitemapIcon;
  position?: number;
  children: TreeNode[];
}

function buildTree(entries: SitemapEntry[]): TreeNode[] {
  return buildTreeWithParents(entries).roots;
}

interface BuiltTree {
  roots: TreeNode[];
  /** child id → parent id (undefined for roots present in entries). */
  parentOf: Map<string, string | undefined>;
}

function buildTreeWithParents(entries: SitemapEntry[]): BuiltTree {
  const byId = new Map<string, TreeNode>();
  const parentOf = new Map<string, string | undefined>();
  for (const e of entries) {
    byId.set(e.id, {
      id: e.id,
      title: e.title,
      ...(e.titleHtml ? { titleHtml: e.titleHtml } : {}),
      href: e.href,
      kind: e.kind,
      icon: e.icon,
      ...(typeof e.position === "number" ? { position: e.position } : {}),
      children: [],
    });
  }
  const roots: TreeNode[] = [];
  for (const e of entries) {
    const node = byId.get(e.id)!;
    if (e.parentId && byId.has(e.parentId)) {
      byId.get(e.parentId)!.children.push(node);
      parentOf.set(e.id, e.parentId);
    } else {
      roots.push(node);
      parentOf.set(e.id, undefined);
    }
  }
  // Sort children by their Notion-supplied `position` when present, falling
  // back to alphabetical for entries we couldn't position (top-level + any
  // page whose parent's child_page blocks didn't surface its id).
  const sortRec = (n: TreeNode[]) => {
    n.sort((a, b) => {
      const ap = typeof a.position === "number" ? a.position : Number.POSITIVE_INFINITY;
      const bp = typeof b.position === "number" ? b.position : Number.POSITIVE_INFINITY;
      if (ap !== bp) return ap - bp;
      return a.title.localeCompare(b.title);
    });
    for (const x of n) sortRec(x.children);
  };
  sortRec(roots);
  return { roots, parentOf };
}

function iconHtml(node: TreeNode, prefix: string): string {
  if (node.icon?.kind === "emoji") {
    return `<span class="tree-emoji" aria-hidden="true">${htmlEscape(node.icon.value)}</span>`;
  }
  if (node.icon?.kind === "image") {
    // Normalize Windows "\" separators in the (relative) icon path to "/".
    const value = node.icon.value.replace(/\\/g, "/");
    return `<img class="tree-icon" src="${prefix}${htmlEscape(value)}" alt="" loading="lazy">`;
  }
  const fallback = node.kind === "database" ? "🗂" : "📄";
  return `<span class="tree-emoji tree-fallback" aria-hidden="true">${fallback}</span>`;
}

// Branch toggle uses a hidden checkbox + label so the chevron and the page link have
// independent hit targets — clicking the chevron expands/collapses, clicking the title
// navigates. No JS needed.
//
// `ancestors`, when provided, is the precomputed Set of node ids on the
// path from the current page up to the root (inclusive of the current page).
// Lookups are O(1) — replaces the old O(N²) `containsId` walk.
function renderBranches(
  nodes: TreeNode[],
  opts: { prefix: string; currentId?: string; idScope: string; ancestors?: Set<string> },
): string {
  if (nodes.length === 0) return "";
  return `<ul class="tree">${renderItems(nodes, opts)}</ul>`;
}

// Emit just the `<li>`s for a list of tree nodes — no surrounding `<ul>`.
// Callers wrap the result in `<ul class="tree">` (top-level) or
// `<ul class="children">` (nested). Keeping the `<ul>` outside this function
// avoids `<ul class="children"><ul class="tree">…</ul></ul>` chains, which
// are invalid per the HTML5 content model (a `<ul>` may only contain `<li>`s).
function renderItems(
  nodes: TreeNode[],
  opts: { prefix: string; currentId?: string; idScope: string; ancestors?: Set<string> },
): string {
  return nodes
    .map((n) => {
      const hasChildren = n.children.length > 0;
      const isActive = n.id === opts.currentId;
      // Ancestor = node whose subtree contains currentId (but not the node itself).
      // The set contains currentId + all parents, so a non-active hit means
      // "ancestor of current".
      const isAncestor = !isActive && (opts.ancestors?.has(n.id) ?? false);
      const open = isActive || isAncestor;
      const linkClass = isActive ? ' class="active" aria-current="page"' : "";
      const href = `${opts.prefix}${htmlEscape(n.href)}`;
      const icon = iconHtml(n, opts.prefix);
      // titleHtml carries inline imgs whose `src="assets/…"` will be rewritten
      // to the page's depth-relative path below via the same regex that handles
      // body images. Fall back to escaped plain title when no titleHtml.
      const titleInner = n.titleHtml ?? htmlEscape(n.title);
      const title = `<a href="${href}"${linkClass} data-id="${n.id}"><span class="tree-title">${titleInner}</span></a>`;
      if (!hasChildren) {
        return `<li class="leaf"><span class="row"><span class="caret-spacer" aria-hidden="true"></span>${icon}${title}</span></li>`;
      }
      const cid = `${opts.idScope}-${n.id}`;
      const checked = open ? " checked" : "";
      const caret = `<label class="caret" for="${cid}" aria-label="Toggle"><svg viewBox="0 0 12 12" width="12" height="12" aria-hidden="true"><path d="M4 2 L8 6 L4 10" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"/></svg></label>`;
      const inner = renderItems(n.children, opts);
      return `<li class="branch"><input class="branch-toggle" id="${cid}" data-id="${n.id}" type="checkbox" hidden${checked}><span class="row">${caret}${icon}${title}</span><ul class="children">${inner}</ul></li>`;
    })
    .join("");
}

function renderTree(nodes: TreeNode[]): string {
  return renderBranches(nodes, { prefix: "", idScope: "ix" });
}

function renderTreeNav(
  nodes: TreeNode[],
  opts: { prefix: string; currentId?: string; ancestors?: Set<string> },
): string {
  return renderBranches(nodes, { ...opts, idScope: "sb" });
}

/** Mutate a rendered sidebar skeleton to mark the active page and pre-expand
 * each ancestor's `<details>`-style toggle. The skeleton is produced once per
 * depth-bucket with no `active`/`checked` markers; this pass is a single
 * regex replace per page (string-replace is linear in skeleton size, not in
 * the page count, so total cost across N pages is O(N · skeleton bytes)
 * rather than O(N²) re-renders).
 */
function applyActiveMarkers(skeleton: string, ancestors: Set<string>, currentId?: string): string {
  let out = skeleton;
  if (currentId && ancestors.has(currentId)) {
    // Active link: add class + aria-current. There is exactly one match.
    // The skeleton's anchor is emitted by `renderItems` as
    // `<a href="…" data-id="…"…>`. We scan for that fixed prefix, then walk
    // back to find the `href="…"` token so we can rebuild the anchor with
    // the active markers inserted between href and data-id — preserving the
    // original quoting and attribute order without paying for a fresh
    // RegExp compile per page.
    const dataAttr = ` data-id="${currentId}"`;
    const idx = out.indexOf(dataAttr);
    if (idx !== -1) {
      // Walk back to the start of `<a `. Anchors never nest, so the nearest
      // preceding `<a ` is ours.
      const aStart = out.lastIndexOf("<a ", idx);
      if (aStart !== -1) {
        const between = out.slice(aStart + 3, idx); // e.g. `href="Foo.html"`
        const replacement = `<a ${between} class="active" aria-current="page"${dataAttr}`;
        out = out.slice(0, aStart) + replacement + out.slice(idx + dataAttr.length);
      }
    }
  }
  // Pre-expand every <input> on the path. Branch inputs only — leaves don't
  // carry an <input>. Ancestors not in the tree (no <input data-id=>) are
  // silent no-ops. Plain string-needle replace — ~3.8k fewer RegExp
  // constructions per export vs. the old `new RegExp(...)` per ancestor.
  for (const id of ancestors) {
    const needle = `<input class="branch-toggle" id="sb-${id}" data-id="${id}" type="checkbox" hidden>`;
    const i = out.indexOf(needle);
    if (i === -1) continue;
    // Replace just the trailing `>` with ` checked>` — cheaper than
    // re-templating the whole needle.
    out = `${out.slice(0, i + needle.length - 1)} checked>${out.slice(i + needle.length)}`;
  }
  return out;
}

// Page templates are written with a `<!--NE_SIDEBAR-->` placeholder so we don't have to
// know the full sitemap at write time. After all entries are collected, this pass walks
// every emitted HTML file and replaces the placeholder with a tree rooted at htmlDir
// (with active-page highlighting + ancestor branches pre-expanded).
export async function injectSidebars(
  htmlDir: string,
  entries: SitemapEntry[],
  opts: { extraFiles?: string[] } = {},
): Promise<void> {
  const { roots, parentOf } = buildTreeWithParents(entries);

  // Skeleton cache, keyed by depth-prefix (e.g. "", "../", "../../"). Most
  // exports have 1-3 unique depths; tree HTML is identical across pages at
  // the same depth aside from the per-page active/checked markers.
  const skeletonCache = new Map<string, string>();
  const skeletonFor = (prefix: string): string => {
    const cached = skeletonCache.get(prefix);
    if (cached !== undefined) return cached;
    let nav = renderTreeNav(roots, { prefix });
    // Rewrite root-relative `assets/<hash>` URLs (from custom-emoji <img>s
    // embedded in titleHtml) so they walk back out of `html/<subdir>/` to
    // the export root's assets/ dir.
    const assetsPrefix = `${prefix}../`;
    // Match both "assets/" and a Windows-produced "assets\" so custom-emoji
    // <img> srcs in titleHtml get the depth-correct "../assets/" prefix.
    nav = nav.replace(/(src|href)="assets[\\/]/g, `$1="${assetsPrefix}assets/`);
    skeletonCache.set(prefix, nav);
    return nav;
  };

  // Walk parents into a Set once per page. O(depth), not O(N). Memoised by
  // node id — ancestor chains overlap heavily across siblings, so each chain
  // is resolved at most once per export.
  const ancestorCache = new Map<string, Set<string>>();
  const ancestorsFor = (id: string): Set<string> => {
    const cached = ancestorCache.get(id);
    if (cached) return cached;
    const set = new Set<string>();
    let cur: string | undefined = id;
    // Guard against cycles in malformed sitemaps.
    while (cur && !set.has(cur)) {
      set.add(cur);
      cur = parentOf.get(cur);
    }
    ancestorCache.set(id, set);
    return set;
  };

  const pool = createPool(24);
  await Promise.all(
    entries.map((e) =>
      pool.run(async () => {
        const fileAbs = path.join(htmlDir, e.href);
        const dir = path.posix.dirname(e.href.split(path.sep).join("/"));
        const depth = dir === "." || dir === "" ? 0 : dir.split("/").length;
        const prefix = "../".repeat(depth);
        const skeleton = skeletonFor(prefix);
        const nav = applyActiveMarkers(skeleton, ancestorsFor(e.id), e.id);
        let html: string;
        try {
          html = await fsp.readFile(fileAbs, "utf8");
        } catch {
          return;
        }
        if (!html.includes("<!--NE_SIDEBAR-->")) return;
        await fsp.writeFile(fileAbs, html.replace("<!--NE_SIDEBAR-->", nav));
      }),
    ),
  );
  // Extra files (stats.html, etc.) carry the marker but aren't sitemap
  // entries — patch them too with a no-active-id skeleton so the sidebar
  // chrome matches the rest of the export.
  const extras = opts.extraFiles ?? [];
  await Promise.all(
    extras.map((rel) =>
      pool.run(async () => {
        const fileAbs = path.join(htmlDir, rel);
        const dir = path.posix.dirname(rel.split(path.sep).join("/"));
        const depth = dir === "." || dir === "" ? 0 : dir.split("/").length;
        const prefix = "../".repeat(depth);
        const skeleton = skeletonFor(prefix);
        let html: string;
        try {
          html = await fsp.readFile(fileAbs, "utf8");
        } catch {
          return;
        }
        if (!html.includes("<!--NE_SIDEBAR-->")) return;
        await fsp.writeFile(fileAbs, html.replace("<!--NE_SIDEBAR-->", skeleton));
      }),
    ),
  );
}

export async function writeSitemap(
  htmlDir: string,
  entries: SitemapEntry[],
  generatedAt: string,
  opts: { searchIndexPath?: string; archiveTitle?: string; archiveIcon?: string } = {},
): Promise<string> {
  const archiveTitle = opts.archiveTitle ?? "Your Notion archive";
  // The index sits at `html/index.html`; assets/ is at the export root, one
  // level up. Walk back out of html/ to reach it.
  const iconRaw = (opts.archiveIcon ?? "").trim();
  const isIconUrl = /^https?:\/\//i.test(iconRaw);
  const isIconImage =
    !!iconRaw &&
    (isIconUrl || iconRaw.includes("/") || /\.(png|jpg|jpeg|svg|webp|gif)$/i.test(iconRaw));
  const iconSrc = isIconUrl ? iconRaw : iconRaw.startsWith("assets/") ? `../${iconRaw}` : iconRaw;
  const heroIcon = !iconRaw
    ? ""
    : isIconImage
      ? `<img class="index-hero-icon" src="${htmlEscape(iconSrc)}" alt="" loading="lazy">`
      : `<span class="index-hero-emoji" aria-hidden="true">${htmlEscape(iconRaw)}</span>`;
  const favicon = isIconImage
    ? renderFavicon({ kind: "image", value: iconSrc })
    : renderFavicon({ kind: "emoji", value: iconRaw || "📚" });
  const tree = buildTree(entries);
  const counts = {
    pages: entries.filter((e) => e.kind === "page").length,
    dbs: entries.filter((e) => e.kind === "database").length,
  };
  const searchTags = opts.searchIndexPath
    ? `<script src="search.js" defer></script>
<script src="lightbox.js" defer></script>
<!-- Lazy-load lunr.min.js + search-index.js on first interaction. -->
<script>${SEARCH_BOOTSTRAP_JS}window.__NE_BOOT_SEARCH("");</script>`
    : `<script src="lightbox.js" defer></script>`;
  const searchBox = opts.searchIndexPath
    ? `<form class="ne-search" onsubmit="return false">
  <input id="ne-search" data-ne-search type="search" placeholder="Search titles or content…" autocomplete="off">
</form>
<ol id="ne-search-results" class="ne-results" hidden></ol>`
    : "";

  // Format the export timestamp as `YYYY-MM-DD HH:mm` (UTC). The
  // page-footer's `Last edited` / `Exported` strings render plain ISO dates,
  // so use the same format here to stay consistent. ISO is unambiguous
  // regardless of viewer locale and survives in the search index unchanged.
  let formattedDate = generatedAt;
  try {
    const d = new Date(generatedAt);
    if (!Number.isNaN(d.getTime())) {
      const iso = d.toISOString();
      formattedDate = `${iso.slice(0, 10)} ${iso.slice(11, 16)} UTC`;
    }
  } catch {
    // fall through with raw timestamp
  }

  const themeWidget = `<div class="topbar-theme index-theme" role="group" aria-label="Theme">
    ${THEME_BUTTONS}</div>`;

  const body = `<header class="index-hero">
  ${themeWidget}
  <div class="index-hero-row">
    ${heroIcon}
    <div class="index-hero-text">
      <h1>${htmlEscape(archiveTitle)}</h1>
      <p class="lede">A static, offline-readable snapshot of your workspace.</p>
    </div>
  </div>
  <dl class="stats">
    <div><dt>Pages</dt><dd>${counts.pages}</dd></div>
    <div><dt>Databases</dt><dd>${counts.dbs}</dd></div>
    <div><dt>Generated</dt><dd>${htmlEscape(formattedDate)}</dd></div>
  </dl>
  <a class="index-stats-card" href="stats.html">
    <span class="index-stats-card-icon" aria-hidden="true">📊</span>
    <span class="index-stats-card-text">
      <span class="index-stats-card-title">Workspace statistics</span>
      <span class="index-stats-card-sub">Edit activity, block-type mix, top-edited pages &amp; more</span>
    </span>
    <span class="index-stats-card-arrow" aria-hidden="true">→</span>
  </a>
  ${searchBox}
</header>
<section class="index-tree">
  <h2 class="section-title">Contents</h2>
  <nav class="tree-root">${renderTree(tree).replace(/(src|href)="assets[\\/]/g, '$1="../assets/')}</nav>
</section>
${renderFooter()}
`;
  const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${htmlEscape(titleForTab(archiveTitle))}</title>
${favicon}
<link rel="stylesheet" href="${STYLE_FILENAME}">
<link rel="stylesheet" href="${KATEX_CSS_FILENAME}">
<script>try{var t=localStorage.getItem('ne-theme');if(t==='dark'||t==='light')document.documentElement.setAttribute('data-theme',t);}catch(e){}</script>
</head>
<body class="index"><div class="layout index">${body}</div>
${searchTags}
</body>
</html>
`;
  const abs = path.join(htmlDir, "index.html");
  await fsp.writeFile(abs, html);
  return abs;
}
